[build-system]
requires = ["setuptools>=67.6", "wheel", "setuptools-scm[toml]>=7.1"]
build-backend = "setuptools.build_meta"

[project]
name = "anonfaces"
version = "1.0.6RC"
requires-python = ">=3.14"
description = "Video/Image anonymization by face detection with a beta stage face recognition"
readme = "README.md"
license = {file = "LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Topic :: Scientific/Engineering :: Image Processing",
    "Topic :: Scientific/Engineering :: Image Recognition",
]

dependencies = [
    "numpy>=1.26.4",
    "tqdm",
    "scikit-image",
    "opencv-python>=4.13.0.92",
    "moviepy>=2.2.1",
    "pedalboard>=0.9.22",
    "onnx>=1.20.1",
    "ffmpeg-python>=0.2.0",
    "imageio>=2.37.3",
    "imageio-ffmpeg>=0.6.0",
]

[project.optional-dependencies]
standard = ["onnxruntime>=1.19.0"]
cuda = ["onnxruntime-gpu>=1.24.3"]
directml = ["onnxruntime-directml==1.19.0"]
openvino = ["onnxruntime-openvino>=1.19.0", "openvino>=2025.0.0"]

[project.scripts]
anonfaces = "anonfaces.anonfaces:main"
faceclean = "anonfaces.helper.cleanup:remove_database"

[tool.setuptools]
packages = ["anonfaces"]

[tool.setuptools.package-data]
anonfaces = [
    "centerface.onnx",
    "shape_predictor_5_face_landmarks.dat",
    "dlib_face_recognition_resnet_model_v1.dat",
	"face_db.sqlite"
]

[tool.setuptools_scm]
write_to = "anonfaces/_version.py"

[tool.ruff]
line-length = 120

[project.urls]
repository = "https://github.com/StealUrKill/anonfaces/tree/RC"
